### PR TITLE
New Node actions for Lua and Python, Multiple Refactors

### PR DESCRIPTION
**Pull request by Bekaboo**
These commits contain node actions for Python and Lua as well as some refactor for `ts-node-action.actions` to improve its extensibility for different filetypes.

### CODE REVIEW

**Comment by CKolkey** [comment]
Outstanding, Ill test this out later. Thanks!

**Comment by Bekaboo** [comment]
> Outstanding, Ill test this out later. Thanks!

Than YOU for this awesome plugin!

P.S. those node actions in `ruby.lua` looks good, and I wonder if we could port some (for example, `toggle_block`, `multiline_conditional`) as general node actions under `actions/`?

P.P.S. It will be better if we have better c/cpp support. Two node actions I always want for c/cpp:

- Toggle between multi-line conditional expressions:

    ```c
    return a > b ? a : b;
    ```

    ```c
    if (a > b) {
        return a;
    } else {
        return b;
    }
    ```

- Toggle between field access operator:

    ```c
    mbi->flags
    ```

    and

    ```c
    mbi.flags
    ```

I tried implementing the field access operator toggler, but did not find a satisfying way since the treesitter parser for c seems to recognize the expression `mbi->flags` as a whole, so we have to do some dirty string manipulation to substitute `->` with `.`; however, this can be thorny when dealing with a more complex field expression like `pcb->pde.pwt`.
`mbi->flags` as a whole

**Comment by CKolkey** [comment]
I'm going to just extract the fix for formatting (`vim.cmd("silent! normal! " .. #replacement .. "==")`) and push that to master so that issue can be resolved separately from these changes. Thanks for pointing that out :)

Ok! To your points:
- I would be happy to port the `toggle_block` and `multiline_condional` functions to be more general purpose. I think the biggest challenge in a more generalized solution is that some languages have a lot more "stuff" to take into consideration. For example, in your `c` code above, the `return` keyword needs to be detected, removed, and prepended to the string. Solvable, but requires a lot more fuss than `ruby`. To that end, it might just be better to build a filetype specific function that can handle these things.

- I'm totally happy to add c/cpp support, but since I don't use them, I don't know what actions would be useful to people! I appreciate the examples here, and if you're keen to take a swing at it, please do :)

**Comment by CKolkey** [comment]
Hi! If you don't mind, I'm going to take this over in this branch: https://github.com/CKolkey/ts-node-action/pull/13

If there's more you'd like to contribute, please just let me know. I really appreciate the work you did - really great stuff!

**Comment by Bekaboo** [comment]
Hi! It's good to know these changes are merged. Looking forward for supports for more languages and code actions.

**Pull request closed without merging**
