### PR TITLE
fix tsnode type for javascript

### PR DESCRIPTION
**Pull request by TroySigX**
method_parameters and argument_list types are changed to arguments

### CODE REVIEW

**Comment by CKolkey** [comment]
Nice! Could you add a quick test? :)

**Comment by TroySigX** [comment]
Sure!

**Comment by TroySigX** [comment]
Hmm, it looks like the tests fail for other filetypes, not javascript. Since, I only modify a small fraction in javascript, it should be fine. Can you look into it, @CKolkey ?

**Comment by TroySigX** [comment]
Honestly, I don't think there is any test to add

**Comment by TroySigX** [comment]
All done, @CKolkey !

**Pull request merged**
