### PR TITLE
feat: actions for sql

### PR DESCRIPTION
**Pull request by matthias-Q**
Add node actions for SQL:

Some note:
* mixed cases are not handled at the moment: e.g. toggling `And` 
* toggling `AND` -> `OR` does not work for some reason.

### CODE REVIEW

**Comment by matthias-Q** [comment]
@alexpw thanks. I saw that after I created the PR. It works, thanks.

**Comment by CKolkey** [comment]
Very nice, thanks for taking the time :) When you can, would you mind adding some specs?

**Comment by matthias-Q** [comment]
I tried adding some specs, but is looks like it is not working. It says is scheduled the test but is does not execute it. Also the run_spec seems to be stuck and does not return to the prompt. Is that as indented?

**Comment by CKolkey** [comment]
Ok! We're in business. You just needed to add the `dofile` line at the top of the spec file, no big deal. Oh, and CI needed the treesitter CLI for SQL. Anyways, you're back in business.

Anyways, the current error: `No action defined for 'sql' node type: 'ERROR'` is because the table passed into `Helper:call()` needs to be valid SQL for the parser. Some parsers are more forgiving than others with respect to incomplete expressions. To fix this you just need to write the smallest possible _valid_ SQL string to pass in that includes the tokens you want to test.

**Comment by matthias-Q** [comment]
Thanks, yes I was missing that. I will add some test cases later today. Thanks

**Comment by matthias-Q** [comment]
Hmm, on my machine the tests are running

**Comment by matthias-Q** [comment]
Ah, I had some indent specified in my dotfiles. They are (not yet) part of nvim-treesitter

**Comment by matthias-Q** [comment]
Is this enough, or do you want more test cases?

**Comment by CKolkey** [comment]
Looks great man!

**Pull request merged**
