### PR TITLE
feat: update julia filetype actions

### PR DESCRIPTION
**Pull request by matthias-Q**
* add julia specific operators
* `toggle_multiline`
* `toggle_boolean` for julia

### CODE REVIEW

**Comment by matthias-Q** [comment]
I have updated the actions for julia and added specs.

**Comment by CKolkey** [comment]
Hell yea. 

Unrelated, what in the APL is this:
```
    ["∉"] = "∈",
    ["∈"] = "∉",
```

**Comment by matthias-Q** [comment]
In Julia, you can use all  utf-8 characters (functions and variables can be emojis... I don't like it). Some of them are shortcuts for functions: e.g. sqrt(x) can be √x
This symbol is the mathematical symbol for "is in" or "is not in"
This is the reason why the parser for julia is so huge (58mb parser.c)

**Comment by CKolkey** [comment]
Ohhh, ok. Ruby lets you do that too, but fortunately all functions are just defined with...words.

**Pull request merged**
